### ISSUE TITLE
something in the mod pack is causing the server to not connect

### ISSUE THREAD

**Issue by NightmareOkami** [elijahjibben/wynncraft-rekindled-modpack#1]
![image](https://github.com/user-attachments/assets/7082e7dc-64e8-494a-839d-d0966b525b86)
it aint wynntils 2.3.23

**Comment by Gravin420** [comment]
same thing happening here.  same result regardless of launcher. no idea what the issue is but it is very frustrating.

**Comment by NightmareOkami** [comment]
> same thing happening here. same result regardless of launcher. no idea what the issue is but it is very frustrating.

found a solution delete fancy menu
